import type { SimpleIcon } from "simple-icons";
import {
  siApollographql,
  siApachekafka,
  siAppium,
  siBitbucket,
  siCloudflare,
  siCss,
  siDocker,
  siElectron,
  siEthereum,
  siEthers,
  siExpress,
  siFirebase,
  siFlask,
  siFlutter,
  siGithub,
  siGithubactions,
  siGmail,
  siGo,
  siGraphql,
  siHtml5,
  siJavascript,
  siJenkins,
  siJest,
  siKubernetes,
  siLangchain,
  siLanggraph,
  siMongodb,
  siMongoose,
  siMui,
  siNestjs,
  siNetlify,
  siNextdotjs,
  siNodedotjs,
  siPolygon,
  siPostgresql,
  siPython,
  siRabbitmq,
  siRadixui,
  siReact,
  siRedis,
  siRedux,
  siRemix,
  siRollupdotjs,
  siRuby,
  siRubyonrails,
  siSelenium,
  siShadcnui,
  siSocketdotio,
  siSolidity,
  siStyledcomponents,
  siSvelte,
  siTailwindcss,
  siTypescript,
  siVercel,
  siVite,
  siVitest,
  siVectorlogozone,
  siWagmi,
  siWeb3dotjs,
  siWebpack,
  siWebrtc,
  siX,
  siYoutube,
} from "simple-icons";

export const skillIcons: Record<string, SimpleIcon | undefined> = {
  LangGraph: siLanggraph,
  LangChain: siLangchain,
  JavaScript: siJavascript,
  TypeScript: siTypescript,
  Go: siGo,
  GoLang: siGo,
  Ruby: siRuby,
  Python: siPython,
  React: siReact,
  Remix: siRemix,
  "Next.js": siNextdotjs,
  SvelteKit: siSvelte,
  Redux: siRedux,
  "Redux Toolkit": siRedux,
  "Material UI": siMui,
  "Styled Components": siStyledcomponents,
  "Tailwind CSS": siTailwindcss,
  "shadcn/ui": siShadcnui,
  "Radix UI": siRadixui,
  HTML: siHtml5,
  CSS: siCss,
  Flutter: siFlutter,
  Electron: siElectron,
  Webpack: siWebpack,
  Vite: siVite,
  Rollup: siRollupdotjs,
  NestJS: siNestjs,
  "Node.js": siNodedotjs,
  Express: siExpress,
  Mongoose: siMongoose,
  Flask: siFlask,
  "Socket.IO": siSocketdotio,
  WebRTC: siWebrtc,
  "Ruby on Rails": siRubyonrails,
  "Ruby On Rails": siRubyonrails,
  MongoDB: siMongodb,
  Redis: siRedis,
  PostgreSQL: siPostgresql,
  Solidity: siSolidity,
  "Web3.js": siWeb3dotjs,
  "Ethers.js": siEthers,
  Wagmi: siWagmi,
  Ethereum: siEthereum,
  Polygon: siPolygon,
  Jest: siJest,
  Vitest: siVitest,
  Selenium: siSelenium,
  Appium: siAppium,
  GraphQL: siGraphql,
  Cloudflare: siCloudflare,
  Firebase: siFirebase,
  Vercel: siVercel,
  Netlify: siNetlify,
  GitHub: siGithub,
  Bitbucket: siBitbucket,
  "Apollo Federation": siApollographql,
  VectorDB: siVectorlogozone,
  Docker: siDocker,
  Kubernetes: siKubernetes,
  "GitHub Actions": siGithubactions,
  Jenkins: siJenkins,
  Kafka: siApachekafka,
  RabbitMQ: siRabbitmq,
};

export const socialIcons: Record<string, SimpleIcon | undefined> = {
  GitHub: siGithub,
  "Twitter/X": siX,
  YouTube: siYoutube,
  Email: siGmail,
  LinkedIn: undefined,
};
